# @package _global_
defaults:
  - /task_class/task/cue_accumulation@task
  - _self_
 
# ---------------------------------------------------------------------------
# Standard cue_accumulation experiment configuration.
# ---------------------------------------------------------------------------
 
# Task-specific parameters
task:
  p: 0.5
  min_delay: 1000
  max_delay: 1001
 
# Network architecture overrides
net_arch:
  sparse_input: true
  sparse_readout: true
 
# Network parameter overrides
net_params:
  k: 0.75
 
# Training parameter overrides
train_params:
  lr: 0.005
  iterations: 2000
  c_reg: 0.005