# @package _global_
defaults:
  - /task_class/task/cue_accumulation@task
  - _self_
 
# ---------------------------------------------------------------------------
# Standard cue_accumulation experiment configuration.
# ---------------------------------------------------------------------------
  

# Network parameter overrides
net_params:
  k: 0.75
 
# Training parameter overrides
train_params:
  lr: 0.005
  iterations: 2000
  c_reg: 0.005
  train_batch_size: 8
  train_mini_batch_size: 8
  test_batch_size: 8
  test_mini_batch_size: 8

  # I tried, didnt change anything for alignment (delayed_match increased a bit the median, but small difference)